Make `importlib-metadata` dependency explicit
### Why?

Builds fail on earlier versions of Python with the following error:

```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    importlib-metadata>=4.8 from https://files.pythonhosted.org/packages/30/bb/bf2944b8b88c65b797acc2c6a2cb0fb817f7364debf0675792e034013858/importlib_metadata-6.6.0-py3-none-any.whl (from sphinx==7.0.1->-r requirements.txt (line 230))
```

This is caused by this Sphinx dependency:

```toml
    "importlib-metadata>=4.8; python_version < '3.10'",
```

### What?

* add explicit dependency on `importlib-metadata`
* `make sync`

### References

* https://github.com/sphinx-doc/sphinx/blob/d3c91f951255c6729a53e38c895ddc0af036b5b9/pyproject.toml#LL72C6-L72C29